# Generated by Django 4.0 on 2022-05-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
