# Generated by Django 2.2.12 on 2021-12-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('variants', models.CharField(max_length=200)),
                ('votes', models.CharField(max_length=200)),
            ],
        ),
    ]
