# Generated by Django 4.0 on 2022-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_poll_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=32)),
                ('session', models.IntegerField()),
            ],
        ),
    ]
