# Generated by Django 4.0 on 2022-01-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
