# Generated by Django 4.0 on 2022-01-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_user_session_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='E4e1c9972cFBcb89B7911dbae7bF5D', max_length=100),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
