# Generated by Django 4.0 on 2022-01-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_poll_author_alter_poll_description_and_more'),
        ('general', '0005_user_salt_alter_poll_description_and_more'),
    ]

    operations = [
    ]
