# Generated by Django 4.0 on 2022-01-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_merge_20220122_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='fcdeBACe5DC2AD775fe1d326C8B3Bd', max_length=100),
        ),
    ]
