# Generated by Django 4.0 on 2022-01-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='8cDabf4B0DFC3CbfB22C0D1ACd49C0', max_length=100),
        ),
    ]
