# Generated by Django 4.0 on 2022-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='DDd33d0c572B55AE73CfB1C4FA3bc6', max_length=100),
        ),
    ]
