# Generated by Django 4.0 on 2022-02-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='CAFd6B1B22006Dde46bA5dDdbb7aE2', max_length=100),
        ),
    ]
