# Generated by Django 4.0 on 2022-02-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='f42921afCa604233da919Ec8809aE1', max_length=100),
        ),
    ]
