# Generated by Django 4.0 on 2022-02-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_user_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('poll', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='variants',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='votes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='Be68FB3aBb2B9F746F62ffF8fABc78', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
