# Generated by Django 4.0 on 2022-02-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_userpoll_alter_poll_description_alter_poll_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('poll', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('A_SC', 'Anonymous_SingleChoice'), ('I_SC', 'Identified_SingleChoice'), ('A_MC', 'Anonymous_MultipleChoice'), ('I_MC', 'Identified_MultipleChoice')], max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPoll',
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='A12E59847d047BDfFd3Ac79fCD5A0F', max_length=200),
        ),
    ]
