# Generated by Django 4.0 on 2022-02-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_alter_voted_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voted',
            name='type',
        ),
        migrations.AddField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('A_SC', 'Anonymous_SingleChoice'), ('A_MC', 'Anonymous_MultipleChoice'), ('I_SC', 'Identified_SingleChoice'), ('I_MC', 'Identified_MultipleChoice')], default='I_SC', max_length=4),
        ),
    ]
