# Generated by Django 4.0 on 2022-02-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_remove_voted_type_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('A_SC', 'Anonymous, single choice'), ('A_MC', 'Anonymous, multiple choice'), ('N_SC', 'Not anonymous, single choice'), ('N_MC', 'Not anonymous, multiple choice')], max_length=4),
        ),
    ]
