# Generated by Django 4.0 on 2022-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_alter_poll_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voted',
            name='selected_option',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
