# Generated by Django 4.0 on 2022-02-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_voted_selected_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voted',
            new_name='Votes',
        ),
    ]
