# Generated by Django 4.0 on 2022-02-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_rename_voted_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
    ]
