# Generated by Django 4.0 on 2022-02-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_rename_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='selected_option',
            field=models.CharField(max_length=200),
        ),
    ]
