# Generated by Django 4.0 on 2022-02-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_alter_vote_selected_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='selected_option',
            new_name='selected_options',
        ),
    ]
