# Generated by Django 4.0 on 2022-02-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_rename_selected_option_vote_selected_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='poll',
            new_name='poll_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='user_id',
        ),
    ]
