# Generated by Django 4.0 on 2022-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_alter_poll_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мen'), ('W', 'Women')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
