# Generated by Django 4.0 on 2022-05-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_temporary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='poll_id',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='selected_options',
            new_name='user_1_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user_2_coordinate',
        ),
        migrations.AddField(
            model_name='vote',
            name='user_1_coordinate',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='user_2_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
