# Generated by Django 4.0 on 2022-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0032_rename_poll_id_vote_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user_1_coordinate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_2_coordinate',
        ),
        migrations.AddField(
            model_name='user',
            name='coordinate',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
