# Generated by Django 4.0 on 2022-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_remove_vote_user_1_coordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='coordinate',
            field=models.TextField(default='Coordinate', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='blablabla', max_length=500),
        ),
    ]
