# Generated by Django 4.0 on 2022-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0034_temporary_coordinate_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='voted_id',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
