# Generated by Django 4.0 on 2022-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0035_posts_voted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='voted_id',
            field=models.CharField(blank=True, default=1, max_length=200),
        ),
    ]
