# Generated by Django 4.0 on 2022-05-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0036_alter_posts_voted_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='voted_id',
        ),
    ]
