# Generated by Django 4.0 on 2022-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0036_message_place_address_message_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='place_address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='place_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
