# Generated by Django 4.0 on 2022-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0037_alter_message_place_address_alter_message_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
