# Generated by Django 4.0 on 2022-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0038_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=200)),
                ('user_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
