# Generated by Django 4.0 on 2022-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0039_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
